version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile

    container_name: sig-laravel-app

    working_dir: /var/www

    restart: unless-stopped

    volumes:
      - ./:/var/www

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - sig-network

  nginx:

    image: nginx:latest

    container_name: sig-nginx

    restart: unless-stopped

    ports:
      - "8000:80"

    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - app

    networks:
      - sig-network

  mysql:

    image: mysql:8.0

    container_name: sig-mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sig_bencana
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

    networks:
      - sig-network

  phpmyadmin:

    image: phpmyadmin/phpmyadmin

    container_name: sig-phpmyadmin

    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

    ports:
      - "8080:80"

    networks:
      - sig-network

  node:

    image: node:22

    container_name: sig-node

    working_dir: /var/www

    tty: true

    restart: unless-stopped

    volumes:
      - ./:/var/www

    networks:
      - sig-network

volumes:
  mysql_data:

networks:
  sig-network:
    driver: bridge